apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vote-namespace.yaml
- vote-deployment.yaml
- vote-service.yaml
- hpa.yaml

images:
- name: docker.io/hutinskit/vote
  newTag: v1.0.36
