apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vote-namespace.yaml
- vote-deployment.yaml
- vote-service.yaml
- vote-ingress.yaml
- hpa.yaml

images:
- name: docker.io/hutinskit/vote
  newTag: v1.0.150
- name: k8s-apps-deployment/k8s-spec-vote/docker.io/hutinskit/vote
  newTag: v1.0.153
