apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vote
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: k8s-apps-deployment/k8s-spec-vote
    repoURL: https://github.com/tinhutins/argocd-vote-deploy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
